version: '3'
services:
  client:
    image: node:14.15.5
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
      - /app/node_modules/
    working_dir: /app
    command:  bash -c "npm install && npm run dev"

  server:
    image: node:14.15.5
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /app/node_modules/
    working_dir: /app
    command: bash -c "npm install && npm run dev"

  
